# Generated by Django 5.2.1 on 2025-06-04 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_useractivity'),
        ('booking', '0004_hotelrating'),
    ]

    operations = [
    ]
